### ISSUE TITLE
Ревизия действующих плагинов на WP Kinoreporter

### ISSUE THREAD

**Issue by taqyon** [atls/kino-reporter#25]
[Кинорепортёр, ревизия плагинов для WP.googlesheetfile](https://docs.google.com/spreadsheets/d/1Tvd50z-V1k-uhBUjWhZ6RLlYeV5t3HWlo7g1NOvekY0/edit#gid=0)

**Comment by taqyon** [comment]
@TorinAsakura добавил [google sheet file.](https://docs.google.com/spreadsheets/d/1Tvd50z-V1k-uhBUjWhZ6RLlYeV5t3HWlo7g1NOvekY0/edit#gid=0) Посмотри если интересно. 

Также я запросил комментарий по ним у «ребят». Посмотрим будет ли он, и если будет то что там будет за комментарий.

**Comment by TorinAsakura** [comment]
Почитал - пока мало что понятно. Комментарии писавшиеся походу в попыхах где не понятен смысл, ну и непонятные статусы плагинов, то есть, пока нельзя работать по этому доку.

**Comment by taqyon** [comment]
В общем они наконец всё посмотрели и отписали комментарии. Ценность всего этого не очень высокая, но в процессе настройки WP я думаю пригодится.
