### ISSUE TITLE
Вариации цветов у кнопок

### ISSUE THREAD

**Issue by carminio** [atls/kino-reporter#39]
@TFK70 

### Проблема
На проекте большое количество кнопок и у них нет нейминга для одинаковых вариаций.

### Например:
Здесь видно что эти две кнопки одинаковые, значит им можно дать один нейминг, как обычно это и делаем, но так как кнопок на проекте много, придется выдумывать какие-то рандомные имена кнопкам и самое главное их будет МНОГО. Рассмотрим такую ситуацию - прошло 20 дней, мне нужно указать вариант стиля кнопке, как она называется в коде я не помню, допустим такая вариация называется **sushi**, а в фигме такого нейминга нет, в таком случае мне придется смотреть цвета стейтов у кнопки в фигме и пробегаться по всем возможным вариантам в файле **colors.ts** на такое же соответствие цветов

![image](https://user-images.githubusercontent.com/35490768/198251582-7960b61b-5da0-49ae-afcd-ce54cdd10d9d.png)

#### В фигме у одинаковых вариантов имена различаются:
А значит придется выдумывать какое-то общение название, которое в фигму не заложено, оно будет только у меня в коде, через какое-то время попробуй определи что за кнопка с названием **sushi**, тут как ни крути придется сидеть и искать соответствие цвета

<img width="611" alt="image" src="https://user-images.githubusercontent.com/35490768/198253404-fcf4f6c0-59d4-4c0a-a4c8-0ed1cff05b79.png">

<img width="611" alt="image" src="https://user-images.githubusercontent.com/35490768/198253579-f9e64a7f-662c-4a76-9e92-e20bae63b643.png">

### Итог
Есть два варианта:

1. То что я делаю сейчас, оставляю комменты с именем вариации кнопки. Тк в будущем будет проще ориентироваться, проще говоря я синхроню свой код и фигму
2.  Использовать имена из фигмы, но в таком случае одинаковые вариации не будут под одним неймингом, вместо имени **sushi** которое объединяло две кнопки со скринов выше, будут как две разные сущности с названиями **otherMonth** и **otherFilter**

**Comment by TFK70** [comment]
@carminio уже понятнее, но всё ещё не понятно

Делай в общем как знаешь пока, если что продолжим здесь обсуждение, оставь задачу

**Comment by TFK70** [comment]
@carminio здесь ещё есть что обсудить? Или всё норм?

**Comment by carminio** [comment]
> @carminio здесь ещё есть что обсудить? Или всё норм?

норм, закрываю 
https://github.com/atls/kino-reporter/pull/40
