### ISSUE TITLE
Не применяются состояния для иконок в Button

### ISSUE THREAD

**Issue by carminio** [atls/kino-reporter#42]
### Описание

@TFK70 

При [текущем подходе](https://github.com/atls/kino-reporter/blob/feat/init-front/ui/button/src/styles/appearance/button.appearance-styles.ts) appearance стилей иконки которые находятся в кнопке не реагируют на состояния.

Попробовал [эти](https://github.com/atls/kino-reporter/blob/feat/init-front/ui/button/src/styles/appearance/button.appearance-styles.ts#L391-L413) стили сделать так:

<details>

```ts
const appearanceCloseSearchDefaultStyles = ({ theme }) => ({
  '&': createAppearanceStyles({
    fontColor: theme.colors.button.closeSearch.default.font,
    backgroundColor: theme.colors.button.closeSearch.default.background,
    borderColor: theme.colors.button.closeSearch.default.border,
  }),
  'svg > path:only-of-type': {
    fill: theme.colors.button.closeSearch.default.font,
  },
})

const appearanceCloseSearchHoverStyles = ({ theme }) => ({
  '&:hover': createAppearanceStyles({
    fontColor: theme.colors.button.closeSearch.hover.font,
    backgroundColor: theme.colors.button.closeSearch.hover.background,
    borderColor: theme.colors.button.closeSearch.hover.border,
  }),
  '&:hover svg > path:only-of-type': {
    fill: theme.colors.button.closeSearch.hover.font,
  },
})

const appearanceCloseSearchPressedStyles = ({ theme }) => ({
  '&:active': createAppearanceStyles({
    fontColor: theme.colors.button.closeSearch.pressed.font,
    backgroundColor: theme.colors.button.closeSearch.pressed.background,
    borderColor: theme.colors.button.closeSearch.pressed.border,
  }),
  '&:active svg > path:only-of-type': {
    fill: theme.colors.button.closeSearch.pressed.font,
  },
})

const appearanceCloseSearchDisabledStyles = ({ theme }) => ({
  '&': createAppearanceStyles({
    fontColor: theme.colors.button.closeSearch.disabled.font,
    backgroundColor: theme.colors.button.closeSearch.disabled.background,
    borderColor: theme.colors.button.closeSearch.disabled.border,
  }),
  'svg > path:only-of-type': {
    fill: theme.colors.button.closeSearch.disabled.font,
  },
})
```

</details>

Теперь иконка реагирует на состояния, но появился артефакт в виде серого бекграунда, который нигде не задан

### Воспроизвести

1. Ветка feat/init-front
2. Запуститься
3. Нажать на инпут в хедере
4. Ввести че нибудь + enter
5. Видим это
<img width="359" alt="image" src="https://user-images.githubusercontent.com/35490768/199700332-1644a0c3-e981-48f9-9b8e-34b21057082f.png">

### Материалы
Серый бекграунд которого не должно быть, тк нигде не задан

<img width="65" alt="image" src="https://user-images.githubusercontent.com/35490768/199698679-bab2e3d1-83a5-45cd-9f7b-e610922c3ea7.png">

https://user-images.githubusercontent.com/35490768/199698816-57a79f3c-dbd3-4111-a76e-6020083afd7e.mov

### Вывод
Нужно в [генераторе button](https://github.com/atls/uikit/blob/master/generators/button/src/style-generators/appearance.style-generator.ts#L25-L29)  добавить возможность менять цвет у иконки, но перед этим разобраться откуда берется бекграунд, тк это решение не до конца корректно отрабатывает

**Comment by TFK70** [comment]
@carminio я думаю это не должно регулироваться через apperance styles самого баттона

Если тебе необходимо менять цвет иконки - тебе нужно менять его напрямую у самой  иконки, а не через стили button. Я могу предложить что-то такое:

```jsx
<Button>
   {(hover) => (
      <CloseIcon color={hover ? 'dark' : 'light'} />
   )}
</Button>
```

**Comment by carminio** [comment]
> @carminio я думаю это не должно регулироваться через apperance styles самого баттона
> 
> Если тебе необходимо менять цвет иконки - тебе нужно менять его напрямую у самой иконки, а не через стили button. Я могу предложить что-то такое:
> 
> ```js
> <Button>
>    {(hover) => (
>       <CloseIcon color={hover ? 'dark' : 'light'} />
>    )}
> </Button>
> ```

допустим, а состояние active как реализовать?

**Comment by TFK70** [comment]
> > @carminio я думаю это не должно регулироваться через apperance styles самого баттона
> > Если тебе необходимо менять цвет иконки - тебе нужно менять его напрямую у самой иконки, а не через стили button. Я могу предложить что-то такое:
> > ```js
> > <Button>
> >    {(hover) => (
> >       <CloseIcon color={hover ? 'dark' : 'light'} />
> >    )}
> > </Button>
> > ```
> 
> допустим, а состояние active как реализовать?

Так же:

```jsx
<Button>
   {(hover, active) => (
      <CloseIcon color={getColor(active, hover)} />
   )}
</Button>
```

Ты должен брать active состояние кнопки, а не иконки. Внутри кнопки можно обычный onClick добавить который будет это состояние отслеживать, так же как с ховером

**Comment by carminio** [comment]
> @carminio я думаю это не должно регулироваться через apperance styles самого баттона

А почему не должно? Иконка такой же айтем как и текст который находится внутри баттона, цвета у них в большинстве случаев (99.9%) не различаются и вместо того, чтобы регулировать через appearance цвета, так как это частый случай, когда состояния иконки === состоянию текста, мы рассматриваем вариант единичных случаев, когда состояния иконки !== состоянию текста, но даже и в этом случае это можно решить через регулирование стилей в appearance styles. Плюс ко всему нужно будет создавать файл getColor который будет громоздким + копипаста так как ничем не будет отличаться от цвета текста из темы для button, на мой взгляд это все лишняя + избыточная работа

**Comment by TFK70** [comment]
> > @carminio я думаю это не должно регулироваться через apperance styles самого баттона
> 
> А почему не должно? Иконка такой же айтем как и текст который находится внутри баттона, цвета у них в большинстве случаев (99.9%) не различаются и вместо того, чтобы регулировать через appearance цвета, так как это частый случай, когда состояния иконки === состоянию текста, мы рассматриваем вариант единичных случаев, когда состояния иконки !== состоянию текста, но даже и в этом случае это можно решить через регулирование стилей в appearance styles. Плюс ко всему нужно будет создавать файл getColor который будет громоздким + копипаста так как ничем не будет отличаться от цвета текста из темы для button, на мой взгляд это все лишняя + избыточная работа

Текст - это часть баттона, а иконка - аддон, отдельная сущность. Если ты используешь в баттоне иконку - это уже частный случай. Иконка - это не строчный элемент, поэтому регулируется отдельно

И лишней работой будет генератор переворачивать с ног на голову. Он уже выполняет свою задачу, других задач у него быть не должно
